[package]
name = "snappy_rs"
version = "0.1.0"
edition = "2021"

# cargo's default, but we want to be explicit
build = "build.rs"
links = "snappy"

[build-dependencies]
cmake = "0.1"

[dependencies]

